# Site settings
title: MY PORTFOLIO
# description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Riccardo Panina
user_description: I'm WebDev based in Milan.
user_title: WebDeloper
email: r.panina@gmail.com
github_username:  panish91

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
